### ISSUE TITLE
How to build the JsonWrapper

### ISSUE THREAD

**Issue by Aerue** [karashiiro/MachinaWrapperJSON#1]
I built a version of MachinaWrapperJSON and placed the ouput in the MachinaWrapper folder. But i think i missed something because i get majoritory some unknown message data on raw event.

For example the `marketBoardItemListing` event not work, but the readme say since IPC opcodes are updated for 5.0 `MarketBoardItemListing = 0x013C, // updated 5.0` there should be no major break of the datas. The `message` event work since i log my own message in game in node.

Here that i did to built a version of MachinaWrapperJSON

1. Cloned this repository
2. Created a `packages` folder into the clone of this repos
3. Downloaded the package of Machina.FFXIV https://www.nuget.org/packages/Machina.FFXIV/2.1.1 into `packages`
4. Builded a version of this repos with msbuild
5. Copied all the outputs files of `MachinaWrapperJSON\MachinaWrapper\bin\Debug` into `node-machina-ffxiv/MachinaWrapper/`

Can you explain me how to build the MachinaWrapperJSON or what i did wrong?

**Comment by karashiiro** [comment]
Sorry for the late reply, didn't get a notification for some reason :v

If you're only getting your own `message` events, you're likely only getting outbound packets, rather than inbound packets from the server. At the moment this requires admin elevation and an explicit firewall rule, but I'm working on removing the firewall rule requirement this week.

**Comment by Aerue** [comment]
Ok i managed to make it work !

But i needed to make a polyfill since i was using typescript and `DataView.prototype.getBigUint64` not work at the moment : https://kangax.github.io/compat-table/esnext/#typescript3_6corejs3

I gonna make a pull request on your other repos for this polyfill.

**Comment by karashiiro** [comment]
Thank you very much! 🙂
