### ISSUE TITLE
Correct way to add/update opcodes?

### ISSUE THREAD

**Issue by p-doyle** [karashiiro/MachinaWrapperJSON#62]
Hello.  I am looking to update an opcode and possibly add a new one.  I thought the Sapphire project was the correct place to do that but it seems that their ipcs.h is only up to 5.35.  Should I open a PR on this project instead or..?

**Comment by karashiiro** [comment]
Feel free, not sure why Sapphire wouldn't accept it, though. To my knowledge their code doesn't need to target a particular game version, since they haven't needed to do updates for any version before 5.3.

But anyways, feel free to PR it here.

**Comment by karashiiro** [comment]
Referencing https://github.com/SapphireServer/Sapphire/pull/705#issuecomment-757334142

**Comment by p-doyle** [comment]
Okay thanks.  Yeah that confused me as well.
